# Generated by Django 5.0.1 on 2026-01-14 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Avatar')),
                ('role', models.CharField(choices=[('client', 'Cliente'), ('booster', 'Booster'), ('admin', 'Administrador')], default='client', max_length=10, verbose_name='Papel')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('discord_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Discord ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_verified', models.BooleanField(default=False, verbose_name='E-mail verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoosterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Avaliação')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='Pedidos concluídos')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de sucesso (%)')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo disponível')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo pendente')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Entrou como booster em')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booster_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Booster',
                'verbose_name_plural': 'Perfis de Boosters',
            },
        ),
    ]
